### PR TITLE
Towards doing the Docker builds from within Maven.

### PR DESCRIPTION
**Pull request by reckart**
**This PR is not ready yet.** - It is more a proposal of integrating the Docker build with the Maven build:

* use a Maven plugin which supports variable replacement in the Dockerfile as not to having to use the Maven resource filtering functionality for this
* also have the Maven plugin inject the MTAS artifact and required datafiles into the Docker image instead of downloading these inside the Dockerfile

I am using this Maven Plugin for the Docker build in WebAnno. But I didn't need to use certain functionalities for WebAnno that would be required for MTAS (i.e. the assembly section in the Docker plugin configuration in the POM). Probably the initial setup in this PR doesn't work... but if the idea sounds reasonable, it could be fixed/improved. If not, I'd prefer not spending time unnecessarily of course ;)

### CODE REVIEW

**Comment by matthijsbrouwer** [comment]
I'm planning to do some changes to our docker setup anyway, so possibly better to postpone. If I understand correctly, this approach creates and pushes docker images instead of just generating the Dockerfile. This may not be the best approach for our (future) production setup, but we will keep this in mind!

**Comment by reckart** [comment]
There are various Docker plugins for Maven. This particular one appeared to me to be the most powerful and flexible one. Yes, it can work with a file template and has commands to build an image, install it locally or push it to a remote repository (amongst other things).

**Comment by reckart** [comment]
A downside of the current approach is that the Dockerfile shows as "modified" in git after each build which (at least for me when switching between branches and preparing pull requests) regularly causes git to complain about locally modified files.

**Comment by reckart** [comment]
Not only when switching branches, also when pulling new changes from this repository:


```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree pull --log origin master 
From https://github.com/meertensinstituut/mtas
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	docker/Dockerfile
Please commit your changes or stash them before you merge.
Aborting
Updating b405b16..52b2687
Completed with errors, see above
```

**Pull request closed without merging**
